### PR TITLE
PyTorch 1.0 Support

### PR DESCRIPTION
**Pull request by adityaarun1**
Updated the code base to support Pytorch 1.0 based on [maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) and [faster-rcnn.pytorch](https://github.com/jwyang/faster-rcnn.pytorch).

P.S.: Needless to say, but there are breaking changes from Pytorch 0.4.0, so you may want to mantain a seperate branch for that.

### CODE REVIEW

**Comment by ruotianluo** [comment]
thank you for your contribution.

**Comment by DHZS** [comment]
Hello @adityaarun1 , I found that the returned values of `RoIAlign` in  pytorch 0.4.0 and 1.0 are different, thus caused different evaluation results.
Here is the APs in pytorch 1.0 version's code.
```
VOC07 metric? Yes
AP for aeroplane = 0.6697
AP for bicycle = 0.7065
AP for bird = 0.6222
AP for boat = 0.5109
AP for bottle = 0.5473
AP for bus = 0.7247
AP for car = 0.8137
AP for cat = 0.7770
AP for chair = 0.4573
AP for cow = 0.7102
AP for diningtable = 0.5086
AP for dog = 0.7451
AP for horse = 0.7839
AP for motorbike = 0.6991
AP for person = 0.7512
AP for pottedplant = 0.3937
AP for sheep = 0.7075
AP for sofa = 0.6124
AP for train = 0.6503
AP for tvmonitor = 0.7017
Mean AP = 0.6547
```

**Comment by adityaarun1** [comment]
@DHZS That's weird. The `ROIAlign` vs `ROIcrop` should not result in that big a difference in AP. I was able to get ~70% mAP with VGG16 on VOC 2007. Let me re-run the code once again to check.

**Comment by adityaarun1** [comment]
@DHZS Hi, I just ran VGG-16 model on VOC 2007 data set and I got 70.5% mAP using default parameter values. Here are the class level details. If you so require, I will be happy to share the log files.
```
AP for aeroplane = 0.7086
AP for bicycle = 0.7885
AP for bird = 0.6965
AP for boat = 0.5595
AP for bottle = 0.5620
AP for bus = 0.7734
AP for car = 0.8502
AP for cat = 0.8253
AP for chair = 0.5209
AP for cow = 0.7668
AP for diningtable = 0.6531
AP for dog = 0.8049
AP for horse = 0.8314
AP for motorbike = 0.7440
AP for person = 0.7791
AP for pottedplant = 0.4562
AP for sheep = 0.6848
AP for sofa = 0.6346
AP for train = 0.7267
AP for tvmonitor = 0.7322
Mean AP = 0.7049
```

**Comment by DHZS** [comment]
Hello @adityaarun1 ,thanks for your help.
Is your model trained in pytorch 1.0? My model was downloaded from here: https://drive.google.com/drive/folders/0B7fNdx_jAqhtNE10TDZDbFRuU0E
It might be trained in pytorch 0.4.0, and it is not compatible well with the code in pytorch 1.0.

**Comment by xiuyangleiasp** [comment]
thank you for your help

**Pull request merged**
